name: 'Bug report'
about: 'Create a report to help us improve'
title: 'Bug found'
labels: bug
assignees: ''

body: 
 - type: textboxes
    attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.

 - type: textboxes
    attributes:
    label: To Reproduce
    description: Steps to reproduce the behavior

 - type: textboxes
    attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.



**Screenshots**
If applicable, add screenshots to help explain your problem.


 - type: textboxes
    attributes:
    label: Additional context
    description: Add any other context about the problem here.

