name: Bug report
labels: [bug]
body: 
 - type: textboxes
    id: bug1
    attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
 - type: textboxes
    id: bugdesc2
    attributes:
    label: To Reproduce
    description: Steps to reproduce the behavior
 - type: textboxes
    id: bugdesc3
    attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.
- type: markdown
  value: "## Screenshots!"
- type: markdown
  attributes:
    value: |
      If applicable, add screenshots to help explain your problem. 
- type: textboxes
    id: bugsesc4
    attributes:
    label: Additional context
    description: Add any other context about the problem here.

