name: Feature request
title: "I would like to get this new feature "
description: true 
labels: [removal]
body:
- type: textarea
  attributes:
    id: probelm1
    label: Is your feature request related to a problem? Please describe.
    description: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]."
  validations:
    required: false
- type: textarea
  attributes:
    id: probelem2
    label: Describe the solution you'd like
    description: "A clear and concise description of what you want to happen."
  validations:
    required: false
- type: textarea
  attributes:
    id: probelem3
    label: Describe alternatives you've considered
    description: "A clear and concise description of any alternative solutions or features you've considered."
  validations:
    required: false
- type: textarea
  attributes:
    id: probelem4
    label: Additional context
    description: "Add any other context or screenshots about the feature request here."
  validations:
    required: false
