name: ❌Remove a site❌
labels: [removal]

body:
- type: textarea
  attributes:
    label: What site do you want to be removed
    description: Add the site you would like to be removed

- type: textarea
  attributes:
    label: Why  would you like to remove that site?
    description: Give a reason why you want to remove the website
