name: 🐞 new site to add
title: "[new site] <site name>"
labels: [addition]
body:
  - type: textboxes
    attributes:
    label: New Site
    description: Please add the site that you want to be added to StopModReposts
 - type: dropdown
    id: version
    attributes:
      label: Version
      description: What site do you want to be added?
      options:
        - Minecraft
        - Skyrim
        - Stardewvalley
        - Subnautica
  - type: textboxes
    attributes:
        label: Anything else?
    description: do you have anything else that you would like to mention
