name: ❌Site to add❌
description: true 
labels: [removal]
body:
- type: textarea
  id: sitereadd
  attributes:
    label: site to be added
    description: "site to be added"
  validations:
    required: true
- type: textarea
  attributes:
    id: anythingwortmention
    label: Do you have anything else worth mentioning?
    description: "Do you have anything else worth mentioning"
  validations:
    required: true
- type: dropdown
  id: whattypeofrepost
  attributes:
    label: What game does the site repost content for? (Example: Minecraft, Subnautica, etc)?
    options:
      - Minecraft
      - Skyrim
      - Stardewvalley
      - Subnauticia
  validations:
    required: true
